### ISSUE TITLE
PA Review: Search

### ISSUE THREAD

**Issue by rachelmoore** [rachelmoore/MeowNow#3]

**Comment by anastassia-b** [comment]
Works awesome, great job!

**Comment by anastassia-b** [comment]
Actually, mapping some data to the markers or otherwise filtering the data upon map click would be a good thing to add.

**Comment by rachelmoore** [comment]
Added infowindows to the map, wasn't that hard: https://developers.google.com/maps/documentation/javascript/infowindows 

Also changed "Search by Location" to "Search by City". 

I could easily link to each individual show page within the infowindow using a simple href tag but I am going to think about that decision for now, I kind of like just having the info.

**Comment by rachelmoore** [comment]
lol I just changed it back to a link and 5 minutes later have decided I like that better. Link to show page it is!

**Comment by anastassia-b** [comment]
Search works great, thanks!
